# docker-compose.yml
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: saferoom-backend
    restart: unless-stopped
    env_file:
      - conf/.env
    environment:
      ENV_PATH: /app/conf/.env
      CAMERA_INDEX: "-1"
      FALLBACK_VIDEO: "data/sample.mp4" 
      TZ: America/Toronto
    volumes:
      - ./conf:/app/conf:ro
      - ./backend/app:/app/app
      - ./backend/data:/app/data            
      - ./backend/models:/app/models
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: saferoom-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    env_file:
      - conf/.env
    environment:
      TZ: America/Toronto
